services:
  db:
    image: mysql:8.0.33
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "db_app:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony_app

  php:
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    ports:
      - 9003:9003
    volumes:
      - ../:/var/www/symfony:cached
      - ./historial_bash/historial_bash:/root/.bash_history # Historial bash persistente
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
      # - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - symfony_app
    tty: true
    stdin_open: true
    working_dir: /var/www/symfony

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/symfony:cached
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    ports:
      - 80:80
      - 8000:8000
    networks:
      - symfony_app
    env_file:
      - .env.nginx.local
    environment:
      NGINX_BACKEND_DOMAIN: localhost

volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_app:

networks:
  symfony_app:
